### ISSUE TITLE
Version name difference between building from source and release binaries

### ISSUE THREAD

**Issue by Sweepi** [etclabscore/go-ethereum#43]
Hi,

I just (190818 ~1500) did a
`git clone https://github.com/etclabscore/go-ethereum.git`
and received the same src (0 differences) as reverenced in https://github.com/etclabscore/go-ethereum/releases (https://github.com/etclabscore/go-ethereum/archive/v6.0.8.zip). However, the version build from source reports
> Geth Classic version: v6.0.6-13-g30d7eed

but the binary release (https://github.com/etclabscore/go-ethereum/releases/download/v6.0.8/geth-classic-v6.0.8-linux.tar.gz) reports

> Geth Classic version: v6.0.8

Did I screw up? Or is there a mistake in the release procedure and the  [release binary](https://github.com/etclabscore/go-ethereum/releases/download/v6.0.8/geth-classic-v6.0.8-linux.tar.gz) has not been build from the [src](https://github.com/etclabscore/go-ethereum/archive/v6.0.8.zip)?

Best regards

__________________________

Edit:
The version number is not in the src, but instead comes from
```go build -o ./bin/geth -ldflags "-X main.Version="`git describe --tags` -tags="netgo" ./cmd/geth```
Since 
`git describe --tags`
returns

> v6.0.6-13-g30d7eed

I now know where the version number originates. I am not working that much with git, therefore I cannot say where it gets the v6.0.6 part from - the other part is the latest commit.
FYI:
`git describe --candidates 10`
also solely returns 

> v6.0.6-13-g30d7eed

**Comment by soc1c** [comment]
Yeah, it needs some love. Currently, there is no way to distinguish between the two release tracks we have. To build the 6.0.8 release, check out the `stable` branch.

**Comment by austinabell** [comment]
When you got the `v6.0.6-13-g30d7eed` version from running geth, were you running a built version or a previously installed version? Since that zip archive of the code does not include the git files, the version will actually be blank. If you want to check the version of the built code to the binary, you can just checkout based on the release tag:

```
git checkout v6.0.9
make build
./bin/geth version
```

I can't replicate the issue you mention here as I get v6.0.9 when I do this and same for v6.0.8.

**Comment by soc1c** [comment]
> I can't replicate the issue

yeah because Greg tagged on development

**Comment by austinabell** [comment]
> yeah because Greg tagged on development

No I can't replicate because when building from the code referenced in their issue relating to the version v6.0.6-13-g30d7eed, there are no git files at all, so the version should be blank. This is why I can't replicate and why I suggested the geth that was run was a previously installed version. 

If you build from the downloaded source based on the link Sweepi provided in the issue do you also get a version number when running? I tried on linux and mac just to make sure and did not get a version on either because there are no git files included at all.

Edit: Or did I misread that the build wasn't done with the link referenced?

**Comment by soc1c** [comment]
Just checkout 30d7eed

And see what `git describe --tags` yields

**Comment by soc1c** [comment]
fixed
